[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['node scripts/copy-videos.js || echo "No videos to copy"', 'npm run build']

[start]
cmd = 'npm start'
